---
default_stages:
  - pre-commit
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make
        args:
          - lint
        always_run: true
        pass_filenames: false
        language: system
      - id: test
        name: test
        entry: make
        args:
          - test
        always_run: true
        pass_filenames: false
        language: system
